
title: BGInfo Extention for Azure (IaSS)
description: Simple way to deploy BGInfo into a virtual machine
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist

github:
  zip_url: https://github.com/adminph-de/ps-azure-bginfo/archive/1.0.zip
  tar_url: https://github.com/adminph-de/ps-azure-bginfo/archive/1.0.tar.gz
  repository_url: https://github.com/adminph-de/ps-azure-bginfo