
title: BGInfo Extention for Azure (IaaS)
description: Simple way to deploy BGInfo into a virtual machine
show_downloads: true
google_analytics: UA-174405517-1
url: "http://github.code-snipes.de/ps-azure-bginfo"
theme: jekyll-theme-modernist

github:
  owner_name: "Patrick Hayo"
  zip_url: https://github.com/adminph-de/ps-azure-bginfo/archive/1.0.zip
  tar_url: https://github.com/adminph-de/ps-azure-bginfo/archive/1.0.tar.gz
  repository_url: https://github.com/adminph-de/ps-azure-bginfo